gemfile: Gemfile

PreCommit:
  BundleCheck:
    enabled: true

  LocalPathsInGemfile:
    enabled: true

  RailsSchemaUpToDate:
    enabled: false

  RuboCop:
    enabled: true
    on_warn: fail
    problem_on_unmodified_line: ignore
    command: ['bundle', 'exec', 'rubocop']

  TrailingWhitespace:
    enabled: true

  YamlSyntax:
    enabled: true

  HardTabs:
    enabled: true
    problem_on_unmodified_line: ignore

PrePush:
  RSpec:
    enabled: true
    command: ["rspec"]